require("prototypes.entity.factory")
require("prototypes.entity.utility")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.style")
require("prototypes.technology")
require("prototypes.tile")
